---
- name: Generate TLS Certificates
  hosts: jumpbox
  tasks:
    - name: Change to working directory
      shell: cd /root/kubernetes-the-hard-way
      
    - name: Generate CA private key
      openssl_privatekey:
        path: /root/kubernetes-the-hard-way/ca.key
        size: 4096
        type: RSA

    - name: Generate CA certificate
      shell: |
        cd /root/kubernetes-the-hard-way
        openssl req -x509 -new -sha512 -noenc \
          -key ca.key -days 3653 \
          -config ca.conf \
          -out ca.crt
      args:
        creates: /root/kubernetes-the-hard-way/ca.crt

    - name: Generate certificate private keys
      openssl_privatekey:
        path: "/root/kubernetes-the-hard-way/{{ item }}.key"
        size: 4096
        type: RSA
      loop:
        - admin
        - node-0
        - node-1
        - kube-proxy
        - kube-scheduler
        - kube-controller-manager
        - kube-api-server
        - service-accounts

    - name: Generate certificate signing requests
      shell: |
        cd /root/kubernetes-the-hard-way
        openssl req -new -key {{ item }}.key -out {{ item }}.csr -config ca.conf -section {{ item }}
      args:
        creates: "/root/kubernetes-the-hard-way/{{ item }}.csr"
      loop:
        - admin
        - node-0
        - node-1
        - kube-proxy
        - kube-scheduler
        - kube-controller-manager
        - kube-api-server
        - service-accounts

    - name: Update kube-api-server certificate with server IP
      replace:
        path: /root/kubernetes-the-hard-way/ca.conf
        regexp: 'DNS\.5 = server\.kubernetes\.local'
        replace: |
          DNS.5 = server.kubernetes.local
          IP.2  = {{ hostvars['server'].ansible_host }}

    - name: Sign certificates with CA
      shell: |
        cd /root/kubernetes-the-hard-way
        openssl x509 -req -in {{ item }}.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
          -out {{ item }}.crt -days 365 -extensions {{ item }}_req_extensions -extfile ca.conf
      args:
        creates: "/root/kubernetes-the-hard-way/{{ item }}.crt"
      loop:
        - admin
        - node-0
        - node-1
        - kube-proxy
        - kube-scheduler
        - kube-controller-manager
        - kube-api-server
        - service-accounts

    - name: Distribute certificates to server
      shell: |
        cd /root/kubernetes-the-hard-way
        scp ca.crt ca.key kube-api-server.key kube-api-server.crt \
            service-accounts.key service-accounts.crt \
            kube-controller-manager.key kube-controller-manager.crt \
            kube-scheduler.key kube-scheduler.crt \
            root@server:~/

    - name: Distribute certificates to workers
      shell: |
        cd /root/kubernetes-the-hard-way
        scp ca.crt {{ item }}.crt {{ item }}.key root@{{ item }}:~/
      loop:
        - node-0
        - node-1