---
- name: Generate Data Encryption Config
  hosts: jumpbox
  tasks:
    - name: Generate encryption key
      shell: head -c 32 /dev/urandom | base64
      register: encryption_key

    - name: Create encryption config file
      copy:
        content: |
          kind: EncryptionConfig
          apiVersion: v1
          resources:
            - resources:
                - secrets
              providers:
                - aescbc:
                    keys:
                      - name: key1
                        secret: {{ encryption_key.stdout }}
                - identity: {}
        dest: /root/kubernetes-the-hard-way/encryption-config.yaml
        mode: '0600'

    - name: Copy encryption config to server
      shell: |
        cd /root/kubernetes-the-hard-way
        scp encryption-config.yaml root@server:~/