---
- name: Bootstrap Kubernetes Worker Nodes
  hosts: workers
  tasks:
    - name: Copy worker binaries from jumpbox
      shell: |
        scp root@jumpbox:/root/kubernetes-the-hard-way/downloads/worker/kubelet \
            root@jumpbox:/root/kubernetes-the-hard-way/downloads/worker/kube-proxy \
            root@jumpbox:/root/kubernetes-the-hard-way/downloads/worker/crictl \
            root@jumpbox:/root/kubernetes-the-hard-way/downloads/worker/runc \
            /root/

    - name: Copy containerd binaries from jumpbox
      shell: |
        scp -r root@jumpbox:/root/kubernetes-the-hard-way/downloads/worker/bin \
               root@jumpbox:/root/kubernetes-the-hard-way/downloads/worker/sbin \
               /root/

    - name: Copy CNI plugins from jumpbox
      shell: |
        scp -r root@jumpbox:/root/kubernetes-the-hard-way/downloads/cni-plugins/* /opt/cni/bin/

    - name: Copy configuration files from jumpbox
      shell: |
        scp root@jumpbox:/root/kubernetes-the-hard-way/configs/containerd-config.toml \
            root@jumpbox:/root/kubernetes-the-hard-way/configs/kubelet-config.yaml \
            root@jumpbox:/root/kubernetes-the-hard-way/configs/kube-proxy-config.yaml \
            root@jumpbox:/root/kubernetes-the-hard-way/configs/10-bridge.conf \
            root@jumpbox:/root/kubernetes-the-hard-way/configs/99-loopback.conf \
            /root/

    - name: Copy systemd unit files from jumpbox
      shell: |
        scp root@jumpbox:/root/kubernetes-the-hard-way/units/containerd.service \
            root@jumpbox:/root/kubernetes-the-hard-way/units/kubelet.service \
            root@jumpbox:/root/kubernetes-the-hard-way/units/kube-proxy.service \
            /root/

    - name: Install worker binaries
      copy:
        src: "/root/{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0755'
        remote_src: yes
      loop:
        - { src: 'kubelet', dest: '/usr/local/bin/kubelet' }
        - { src: 'kube-proxy', dest: '/usr/local/bin/kube-proxy' }
        - { src: 'crictl', dest: '/usr/local/bin/crictl' }
        - { src: 'runc', dest: '/usr/local/bin/runc' }

    - name: Install containerd binaries
      shell: |
        cp -r /root/bin/* /usr/local/bin/
        cp -r /root/sbin/* /usr/local/sbin/

    - name: Create worker directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/cni/net.d
        - /opt/cni/bin
        - /var/lib/kubelet
        - /var/lib/kube-proxy
        - /var/lib/kubernetes
        - /var/run/kubernetes
        - /etc/containerd

    - name: Configure CNI bridge network
      template:
        src: ../templates/10-bridge.conf.j2
        dest: /etc/cni/net.d/10-bridge.conf
        mode: '0644'
      vars:
        pod_cidr: "{{ hostvars[inventory_hostname].pod_cidr }}"

    - name: Install CNI loopback configuration
      copy:
        src: /root/99-loopback.conf
        dest: /etc/cni/net.d/99-loopback.conf
        mode: '0644'
        remote_src: yes

    - name: Install containerd configuration
      copy:
        src: /root/containerd-config.toml
        dest: /etc/containerd/config.toml
        mode: '0644'
        remote_src: yes

    - name: Move kubelet certificates
      copy:
        src: "/root/{{ item }}"
        dest: "/var/lib/kubelet/{{ item }}"
        mode: '0600'
        remote_src: yes
      loop:
        - "{{ inventory_hostname }}.crt"
        - "{{ inventory_hostname }}.key"
        - ca.crt

    - name: Rename worker certificate files
      shell: |
        mv /var/lib/kubelet/{{ inventory_hostname }}.crt /var/lib/kubelet/kubelet.crt
        mv /var/lib/kubelet/{{ inventory_hostname }}.key /var/lib/kubelet/kubelet.key

    - name: Move kubelet kubeconfig
      copy:
        src: "/root/{{ inventory_hostname }}.kubeconfig"
        dest: /var/lib/kubelet/kubeconfig
        mode: '0600'
        remote_src: yes

    - name: Install kubelet configuration
      copy:
        src: /root/kubelet-config.yaml
        dest: /var/lib/kubelet/kubelet-config.yaml
        mode: '0644'
        remote_src: yes

    - name: Move kube-proxy kubeconfig
      copy:
        src: /root/kube-proxy.kubeconfig
        dest: /var/lib/kube-proxy/kubeconfig
        mode: '0600'
        remote_src: yes

    - name: Install kube-proxy configuration
      copy:
        src: /root/kube-proxy-config.yaml
        dest: /var/lib/kube-proxy/kube-proxy-config.yaml
        mode: '0644'
        remote_src: yes

    - name: Install systemd service files
      copy:
        src: "/root/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        mode: '0644'
        remote_src: yes
      loop:
        - containerd.service
        - kubelet.service
        - kube-proxy.service

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start containerd
      systemd:
        name: containerd
        enabled: yes
        state: started

    - name: Enable and start kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started

    - name: Enable and start kube-proxy
      systemd:
        name: kube-proxy
        enabled: yes
        state: started

    - name: Wait for kubelet to register with API server
      pause:
        seconds: 30